#!/usr/bin/env bash
# script : change pulseaudio volume & send a notification

# function
notify () {
    vol=$(amixer -D pulse sget Master | grep -oP '\d{1,3}%' | head -n 1)
    notify-send.sh -r 22 "Volume: $vol"
}

# options
case "$1" in
    up)
	amixer -D pulse sset Master 5%+
        notify
        ;;
    down)
        amixer -D pulse sset Master 5%-
        notify
        ;;
    mute)
        amixer -D pulse sset Master mute
        notify-send.sh -r 22 'Volume: toggle mute'
        ;;
esac
