#!/usr/bin/env bash
# script : change brightness & send a notification

# function
notify () {
    br=$(xbacklight -g | cut -c 1-3 | tr -d '.')
    notify-send.sh -r 22 "Brightness: $br"%""
}

# options
case "$1" in
    up)
        xbacklight -inc 5
        notify
        ;;
    down)
        xbacklight -dec 5
        notify
        ;;
esac
