#!/usr/bin/env bash
# script : change pulseaudio volume & send a notification

# function
notify () {
    vol=$(amixer sget Master | grep -oP '\d{1,3}%' | head -n 1)
    notify-send.sh -r 22 "Volume: $vol"
}

# options
case "$1" in
    up)
        pactl set-sink-volume 0 +5%
        notify
        ;;
    down)
        pactl set-sink-volume 0 -5%
        notify
        ;;
    mute)
        pactl set-sink-mute 0 toggle
        notify-send.sh -r 22 'Volume: toggle mute'
        ;;
esac
